version: '3.9'

services:
  data:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=yourStrongPassword12#$
    volumes:
      - sqldata:/var/opt/mssql
    networks:
      - stockrestapi
    restart: on-failure

  database:
    container_name: database
    image: stockrestapidb
    build:
        dockerfile: ./StockRestApi.Database/StockRestApi.Database/Dockerfile
    ports:
      - "5500:80"
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=StockRestApi1;User Id=sa;Password=yourStrongPassword12#$;MultipleActiveResultSets=true;encrypt=False
    volumes:
      - data-protection:/root/.aspnet/DataProtection-Keys
    networks:
      - stockrestapi
    depends_on:
      - data
    restart: on-failure
    
networks:
  stockrestapi:

volumes:
  sqldata:
  data-protection: