version: '3.9'
name: stock-rest-api

services:
  sql_server:
    container_name: sql_server
    image: mcr.microsoft.com/mssql/server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=yourStrongPassword12#$
    volumes:
      - sqldata:/var/opt/mssql
    networks:
      - mynetwork
    restart: on-failure

  gateway:
    container_name: gateway
    build:
        context: StockRestApi.Gateway/
        dockerfile: Dockerfile
    environment:
      - ASPNETCORE_HTTP_PORT=https://+:443
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "8080:80"
      - "8088:443"
    volumes:
      - data-protection:/root/.aspnet/DataProtection-Keys
    networks:
      - mynetwork
    depends_on:
      - sql_server
    restart: on-failure

  accounts:
    container_name: accounts
    build:
      context: StockRestApi.Accounts/
      dockerfile: Dockerfile
  
    environment:
      - ASPNETCORE_HTTP_PORT=https://+:443
      - ASPNETCORE_URLS=http://+:80
  
    volumes:
      - data-protection:/root/.aspnet/DataProtection-Keys
    networks:
      - mynetwork
    depends_on:
      - sql_server
      - gateway
    restart: on-failure
    
networks:
  mynetwork:

volumes:
  sqldata:
  data-protection: